# Generated by Django 4.1.2 on 2022-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("image", models.ImageField(null=True, upload_to="images")),
                ("description", models.CharField(max_length=32)),
                ("url", models.URLField()),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=32)),
            ],
        ),
    ]
