# Generated by Django 4.1.2 on 2022-10-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
