# Generated by Django 4.1.2 on 2022-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="card",
            name="username",
            field=models.CharField(max_length=128),
        ),
    ]
