# Generated by Django 4.1.2 on 2022-11-03 08:46

from django.db import migrations, models


def reorder(apps, schema_editor):
    MyModel = apps.get_model("cards", "Card")
    for order, item in enumerate(MyModel.objects.all(), 1):
        item.my_order = order
        item.save(update_fields=['my_order'])


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_password_alter_card_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="card",
            name="my_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
