# Generated by Django 4.1.2 on 2022-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_password_alter_card_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="tags",
            field=models.ManyToManyField(to="cards.tag"),
        ),
    ]
