# Generated by Django 4.1.2 on 2022-11-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_alter_card_options_card_my_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="tags",
            field=models.ManyToManyField(blank=True, to="cards.tag"),
        ),
    ]
